{-# OPTIONS  #-}


-- parser (data) produced by Happy (GLR) Version 1.18.6

module syntaxData where




{-# LINE 1 "templates/GLR_Base.hs" #-}
{-# LINE 1 "templates/GLR_Base.hs" #-}
{-# LINE 1 "<built-in>" #-}
{-# LINE 1 "<command-line>" #-}
{-# LINE 1 "templates/GLR_Base.hs" #-}
{- GLR_Base.lhs
   Id: GLR_Base.lhs,v 1.4 2004/12/04 15:01:37 paulcc Exp 
-}

-- Basic defs required for compiling the data portion of the parser

-- We're creating Int-indexed graphs

type ForestId  = (Int,Int,GSymbol)


-- Actions for the GLR machine

data GLRAction = Shift Int [Reduction]
               | Reduce [Reduction]
               | Accept
               | Error

---
-- A Reduction (s,n,f) removes the top n node-ids, creates a new branch from these
-- and labels the branch with the given symbol s. Additionally, the branch may
-- hold some semantic value.

type Reduction = (GSymbol,Int, [ForestId] -> Branch)


---
-- A Branch holds the semantic result plus node ids of children

data Branch
 = Branch {b_sem :: GSem, b_nodes :: [ForestId]}
   deriving Show

instance Eq Branch where
	b1 == b2 = b_nodes b1 == b_nodes b2



-------------------------------------------------------------------------------
-- Utilities for decoding

---
-- Tree decode unpacks the forest into a list of results
--  - this is ok for small examples, but inefficient for very large examples
--  - the data file contains further instances
--  - see documentation for further information
--  - "Decode_Result" is a synonym used to insert the monad type constr (or not)

class TreeDecode a where
	decode_b :: (ForestId -> [Branch]) -> Branch -> [Decode_Result a]

decode :: TreeDecode a => (ForestId -> [Branch]) -> ForestId -> [Decode_Result a]
decode f i@(_,_,HappyTok t)
  = decode_b f (Branch (SemTok t) [])
decode f i
  = [ d | b <- f i, d <- decode_b f b ]

---- generated by Happy, since it means expansion of synonym (not ok in H-98)
--instance TreeDecode UserDefTok where
--	decode_b f (Branch (SemTok t) []) = [happy_return t]

---
-- this is used to multiply the ambiguous possibilities from children

--cross_fn :: [a -> b] -> [a] -> [b]
--actual type will depend on monad in use.
--happy_ap defined by parser generator
cross_fn fs as = [ f `happy_ap` a | f <- fs, a <- as]

---
-- Label decoding unpacks from the Semantic wrapper type
--  - this allows arbitrary values (within the limits of the compiler settings)
--    to be recovered from nodes in the tree.
--  - again, more instances are written in the data file
--  - see documentation for further information

class LabelDecode a where
	unpack :: GSem -> a

---- generated by Happy, since it means expansion of synonym (not ok in H-98)
--instance LabelDecode UserDefTok where
--	unpack (SemTok t) = t




{-# LINE 100 "syntaxData.hs"#-}

parseError :: [Token] -> a
	parseError _ = error "Parse error"

	data Token = TokenIdentifier String

	data EndState = EndState TokenIdentifier

{-# LINE 109 "syntaxData.hs"#-}

data GSymbol = HappyEOF | HappyTok {-!Int-} (Token) | G_File 
 | G_Expr 
 | G_Endstate 
   deriving (Show,Eq,Ord)

data GSem
 = NoSem
 | SemTok (Token) | Sem_0 (()) 
 | Sem_1 (()) 
 | Sem_2 (()) 
   deriving (Show)


semfn_0_0 ns@(happy_rest) =  Branch (Sem_0 ([])) ns
semfn_1_0 ns@(happy_var_1:happy_var_2:happy_var_3:happy_rest) =  Branch (Sem_1 (happy_var_1 : happy_var_3)) ns
semfn_2_0 ns@(happy_var_1:happy_rest) =  Branch (Sem_2 (happy_var_1)) ns
semfn_2_1 ns@((_,_,HappyTok (happy_var_1@())):happy_rest) =  Branch (Sem_2 (EndState happy_var_1)) ns


type Decode_Result a = a
happy_ap = ($)
happy_return = id
instance LabelDecode (()) where 
	unpack (Sem_0 s) = s
	unpack (Sem_1 s) = s
	unpack (Sem_2 s) = s


type UserDefTok = Token
instance TreeDecode (Token) where
	decode_b f (Branch (SemTok t) []) = [happy_return t]
instance LabelDecode (Token) where
	unpack (SemTok t) = t


action 0 ( HappyTok () ) = Shift 5 []
action 0 ( HappyEOF ) = Reduce [red_1]
action 2 ( HappyEOF ) = Accept
action 3 ( HappyTok () ) = Shift 7 []
action 4 ( HappyTok () ) = Reduce [red_3]
action 5 ( HappyTok (TokenIdentifier _) ) = Shift 6 []
action 6 ( HappyTok () ) = Reduce [red_4]
action 7 ( HappyTok () ) = Shift 5 []
action 7 ( HappyEOF ) = Reduce [red_1]
action 8 ( HappyEOF ) = Reduce [red_2]
action _ _ = Error
red_1 = (G_File,0 :: Int,semfn_0_0)
red_2 = (G_File,3 :: Int,semfn_1_0)
red_3 = (G_Expr,1 :: Int,semfn_2_0)
red_4 = (G_Endstate,2 :: Int,semfn_2_1)
goto 0 G_File = 2
goto 0 G_Expr = 3
goto 0 G_Endstate = 4

goto 7 G_File = 8
goto 7 G_Expr = 3
goto 7 G_Endstate = 4

goto _ _ = -1
