include LaTeX.mk

dot: computability/completeness/pictures/binary-adder.dot
					dot -o computability/completeness/pictures/binary-adder.png -Tpng computability/completeness/pictures/binary-adder.dot
